<?php

namespace authenBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * clientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clientRepository extends EntityRepository
{

}
