<?php

namespace authenBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MgUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MgUserRepository extends EntityRepository
{
}
